---
title: "Linux란"
author: "Siheon Jo"
date: "2023-01-05"
categories: [Linux]
---

# Linux
## 리눅스와 타 OS의 차이
### 타 OS
- 윈도우나 Mac OS 등은 개발자가 아닌 end-user들을 대상으로 만든 운영체제
- 가능한 어려운 조작 없이 Graphic User Interface (GUI)로 만들어진 화면에서 개발자가 만든 프로그램을 사용
  - GUI란 모든 요소들이 그림으로 나타나서 사용자가 마우스로 클릭해서 사용할 수 있음
- 일반 사용자 입장에서 배우기 쉽고 사용하기 편함
- 각종 프로그램들도 GUI 위주로 만듦
### Linux
- Linux는 CUI로 사용 할 수 있게함
- GUI는 완제품의 느낌이라면 CLI는 조립식 제품이라고 생각할 수있음
- 리눅스는 오픈소스라서 다양하게 개조하고 발전 시킬 수 있음
- 서버는 특정 OS로 사용하는데 일반 개발자로서는 뭔가를 개발하기위한 진입장벽이 높지만 리눅스는 서버에 깔아서 사용할 수 있다. 대표적으로 안드로이드가 있다.

## 리눅스의 '커널'이란
리눅스의 커널이 곧 리눅스다.

리눅스가 칼이라면 커널은 칼날이다.

CPU Memory Device 등을 직접 다루고 관리하는게 커널이다.

- 리눅스 종류는 대중적인 대표인 UBUNTU 사용

## 리눅스 사용
리눅스 환경 즉 리눅스가 깔린 기기가 필요
1. 가상머신 소프트웨어
  - VirtualBox로 사용
  - UBUNTU사이트에 CLI SERVER 다운받아 사용
  - VirturalBox에서 다운받은 ios 파일 사용
2. 온라인 IDE/터미널
  - Goormide 가입 새컨테이너 생성 Blank 생성해서 브라우저에서 사용 가능
  - AWS Cloud9
  - Google Compute engine
3. 윈도우 10의 WSL

## 리눅스 기본적인 명령어
|명령어|설명|예시|
|------|----------------------------|--------------|
|pwd|현재 위치한 디렉토리의 절대경로 표시|```pwd```|
|ls|현재 위치한 디렉토리 내 파일/디렉토리 목록을 표시|```ls```|
|cd {경로}|경로로 이동하는 명령어|```cd home/siheon```|
|mkdir {디렉토리명}|폴더 생성|```mkdir sample_file```|
|vi||vi 에디터 실행 :wq로 저장해야 만들어지고 :q를 만들면 종료되고 i를 누르면 내용 입력 가능|```vi sample.txt```|
|cp {복사할 대상} {붙여넣을 경로 또는 새 파일명}|파일을 복사 디렉토리를 복사할 시에는 -r을 붙여야함|```cp original.txt copied.txt``` or ```cp original.txt ../anothorfolder```|
|mv {옮길 대상} {옮길 위치}|파일이나 디렉토리를 옮기거나 이름을 변경할때 예약|```mv original.txt ../anotherfolder/```|
|rm {삭제할 대상}|파일이나 디렉토리 삭제 -r을 할시 재귀적으로 살펴보아 내부 내용까지 다 삭제|```rm fileTodelete.txt``` or ```rm -r folderToDelete```|
|sudo {명령어}|관리자 권한으로 실행|```sudo apt update```|


### 옵션
|명령어|설명|
|------|----------------------------|
|-a|숨긴 파일을 포함한 모든 항목 표시|
|-d|디렉토리 정보만 표시|
|-F|디렉토리는 /, 실행가능 파일은 \*,소켓 파일은 =,링크인 경우 @를 파일이음 뒤에 표시|
|-l|각 항목의 상세 정보들을 함께 표시|
|-m|각 항목들을 쉼표로 구분하여 표시|
|-r|항목들을 역순으로 표시|
|-R|하위 디렉토리의 내용들도 표시|
|-s|kb단위로 표시|
|-t|최종 수정시간을 기준으로 표시|
|-u|최종 액세스 시간 기준으로 표시|

## Vim을 익힐수 있는 사이드
[Vim adventure](https://vim-adventures.com/) : 게임 형식으로 Vim 학습
[OpenVim](https://www.openvim.com/) : 주요 기능들을 쉽게 가이드하는 웹 튜토리얼
[VimGenius](http://www.vimgenius.com/) : 퀴즈 형식으로 Vim을 연습