# Quarto 프로젝트 파일
project:
  type: website

website:
  title: "blogfile"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joesiheon496/
format:
  html:
    theme: cosmo
    css: styles.css



