---
title: "컴퓨터 Network 공부"
author: "Siheon Jo"
date: "2023-01-23"
categories: [Network]
---
# 컴퓨터 네트워크란?
## 컴퓨터 네트워크와 인터넷
### 네트워크
- 종단 시스템(end system): PC나 스마트폰처럼 네트워크 송수신 주체
- 프로토콜(Protocol): 두 이종 시스템을 연결하기 위한 규약
- 통신을 목적으로 실제 물리적으로 선으로 연결되어 있거나 무선으로 연결됨

### 인터넷
- 회사 혹은 소규모의 네트워크에서 전세계 네트워크와 연결된 상태
- 다양한 애플리케이션 서비스가 제공되고 있다.
- 종단 시스템은 보통 ISP(Internet Service Provider)에 의해 연결

### OSI 7계층 (Layer)
- 네트워크 구성요소를 7개의 계층으로 역할을 나눈 표준 모델
- 각 계층별 역할을 통해 통신 규격(프로토콜)을 만족
- 일부 하위계층은 하드웨어에서 구현되며 상위계층은 소프트웨어로 구현

### TCP/IP (Transmission Control Protocol/Internet Protocol)
- OSI 7계층이 나오기전 널리 사용되던 사실상 표준 역할
- 각 계층별 역할에 따라 역할이 나누어짐

### IP 주소(Address)
- 통신 자료를 최종적으로 전달하기 위해 필요한 송/수신 위치정보
- 보통 IPv4의 주소를 사용하며 주소 부족을 위해 IPv6가 개발됨

### 패킷 교환(Packet Switching)
- 종단간에 전송되는 데이터를 패킹(Packet)이라는 단위로 전달함
- 패킷은 네트워크를 통해 일정한 순서없이 보내지며 어떤 경로를 통해 이동되는지는 네트워크의 상황에 따라 다르다.

## 통신을 위한 기본 동작
### 요청(Request)
- 전송하는 종단 장치에서 상대방에 서비스를 요청한다.

### 인지(Indicate)
- 수신하는 장치에서 작업 요청(이벤트)을 확인한다.

### 응답(Response)
- 수신하는 장치에서 요청받은 작업에 대해 적절히 응답한다.

### 확인(Confirm)
- 전송 측에서 응답 데이터를 최종적으로 확인한다.

## 네트워크의 유형
### LAN (Local Area Network)
- 일정 그룹의 지역 네트워크 (집, 사무실, 학교 등)
- 소규모로 묶이며 사설망등을 구축해 연결
### WAN (Wide Area Network)
- 원거리 통신망으로 넓은 범위 연결 (국가, 대륙 등)
### 크기 유형
- LAN < WAN < Internet
## 네트워크 토폴로지(네트워크 구성 형태)
- Ring Topology
    - 기기끼리 서로 연결
    - 장점: 기기와 기기간의 연결이기 때문에 회선설치가 수월하다
    - 단점: 장비가 불량이 생겼을 경우에는 특정 장비에게 통신하기 어려워진다.
- Bus Topology
    - 하나의 메인 회선을 설치하고 메인 회선에 연결해 놓는 형태이다.
- Star Topology
    - 허브가 있고 허브에 기기를 연결하는 형태
    - 허브의 위치에 따라 회선을 끌어와야 하기 때문에 설치가 힘들 수 있다.
- Mesh Topology
    - 하나의 장비가 여러개의 회선을 가지고 다수의 장비에 연결된다.
    - 가장 빠르고, 하나가 고장나더라도 통신이 가능하다.
    - 회선 설치가 복잡해진다.
## 네트워크의 계층별 역할
### OSI 7 Layer와 TCP/IP의 관계
Physical -> Datalink -> network -> transporter -> session -> presentation -> application
(                   Kernel                    )  (           User Process               )
- Physical: 일련의 2진 bit(전기적 신호를 매체로 전달)
- Datalink: 두 node간의 통신관여, 흐름제어
- Network: 해당주소 체계에 따라 경로 설정
- Transport: 양쪽 끝간의 신뢰성 보장
- Session: 프로그램간의 논리적 접속
- Presentation: 문법, 구문, 체계 확림
- Application: Email, Web 브라우저, FTP, ping, Appl
- 데이터 -> Application -> Transport(Packing) -> Network(주소) -> Data Link(하드웨어 주소)-> Physical(1과 0의 형태의 이진 값으로 전달) -> 경로를 알기위해 네트워크 계층까지 역으로 확인 -> 목적지에 도착한다면 역으로 진행됨

### 물리계층(Physical layer)
-개요
    - 물리적 매체를 통한 비트 스트림(비트를 보내는 과정) 전송에 요구되는 기능을 담당(기계적, 전기적, 전송매체)
    - 물리적인 장치와 인터페이스가 전송을 위해 필요한 기능과 처리절차 규정
- 물리 층의 주요기능
    - 인터페이스와 매체의 물리적인 특성: 장치와 전송매체 간의 인터페이스 특성을 규정
    - 비트의 표현: 비트를 전송하기 위해 전기적 또는 광학적인 신호로 부호화
    - 데이터 속도: 신호가 유지되는 비트의 주기를 규정
    - 비트의 동기화: 송신자와 수신자는 같은 클록(얼마나 빠른지에 따라서 비트 데이터를 받을 수 있음)을 사용
- MAC(Medium Access Control) 필요
    - 자유경쟁 (선착순)
        - Aloha
        - Slotted Aloha - 간격 할당
        - CSMA(Carrier Sense Multiple Access)
        - CSMA/CD(CSMA/Collison Detection)
    - Token
- CSMA/CD -> IEEE 802.3
    - 한 slot의 크기 잼 신호
        =51.2us = 64byte 전송소요 시간
    - 16번까지 재시도
### 데이터 링크 계층(Data link layer)
- 개요
    - 노드대 노드 전달(node-to-node delivery)의 책임
- 기능
    - 프레임 구성: 네트워크 계층으로부터 받은 비트 스트림을 프레임단위로 나눔
    - 물리주소 MAC (Medium Access Control) 지정: 송신자와 수신자의 물리 주소를 헤더에 추가
    - 흐름제어: 수신자의 수신 데이터 전송률을 고려하여 데이터 전송하도록 제어
    - 오류제어: 손상 또는 손실된 프레임을 발견/재전송, 트레일러를 통해 이루어짐
    - 접근제어: 주어진 어느 한 순간에 하나의 장치만 동작하도록 제어
#### 데이터 링크 계층에서 사용하는 주요 프로토콜
- ARP(Address Resolution Protocol)
    - 주소를 해석하기 위한 프로토콜
    - 논리적인 IP 주소를 물리적인 MAC주소로 바꾼다.
    - 캐시를 통해 얻은 정보가 저장되고 보통 20분의 수명을 가진다.
- RARP(Reserve Address Resolution Protocol)
    - 역 주소 프로토콜
    - 저장 장치가 없는 네트워크 단말기등이 IP 주소를 얻기위해 사용
- node-to-node = hop-to-hop
- 물리주소의 데이터 전달 과정
    - 물리주소 10인 노드는 물리주소 87인 노드에 프레임을 보낸다.
        - Ex) 07:01:02:01:2C:4B
    - 데이터 링크 수준에서 이 프레임은 헤더에 물리주소들을 가지고 있다. 여기서는 오직 이 주소들만 필요하다.
    - 헤더의 끝에는 이 수준에서 필요한 다른 정보가 있다. 트레일러에는 보통 오류검출을 위한 추가 비트들이 포함되어 있다.
# 각 계층별 프로토콜의 역할

# 네트워크 응용

# 네트워크 프로그래밍