---
title: "선수지식 - 통계"
author: "Harlow Malloc"
date: "2023-01-05"
categories: [통계]
---

# 확률 개요
딥러닝의 기초가 되는 확률 개념 알아보기
확률이란 특정한 사건이 일어날 가능성을 수로 표현한 것을 의미한다
확률을 0부터 1(100%) 사이의 실수로 표현된다.

가능성을 수로 표현할 수 있어 수학적으로 접근 가능

확률이 사용되는 예시
스팸 메일 분류 모델을 만들고 싶다고 가정
지금까지 도착한 메일 총 1000개
이중에서 700개는 스펨메일 300개는 정상메일
그것이 스펨 메일일 확률을 70%

데이터의 특성을 파악해서 확률적으로 접근할 필요가 있음

기계학습은 확률적으로 이해 가능

N개의 학류 ㄹ데이터로 기계학습 모델을 학습
기계학습 모델의 출력은 "확률"형태를 띤다

학습데이터(x1,y1),...(xn,yn)-> 학습 알고리즘->기계학습 모델 theta <-테스트 데이터x -> 출력 y

다양한 문제 상황에서의 경우의 수를 이해해야한다
경우의 수를 계산하는 방법으로는 순열(permutation)과 조합(combination)을 이해해야한다

순열이란 서로 다른 n개에서 r개를 중복 없이 뽑아 특정한 순서로 나열하는 것을 의미한다
모든 순열의 경우는 다음의 공식으로 계싼할 수 있다

1) 순열의 수 공식(n=r일때)
nPr=n!
2) 순열의 수 공식(n=/r일 때)
참고 0!은 1이다

nPr=n!/(n-r)!

순열이 활용되는 예시
기계 학습 모델 학습을 위해 N개의 학습 데이터로 학습진행하는데
이때 매번(epoch)모델에 학습 데이터를 ㄴ허을 순서를 섞어서(shuffling) 학습을 진행한다.
에포크(epoch): 학습 데이터 세트에 포함된 모든 데이터가 한 번씩 모델을 통과한 횟수를 말한다.
여기서 순서가 바뀌어서 들어갈 수 있다.

3개의 이미지가 있을때
모든경우 [1,2,3] [1,3,2] [2,1,3] [2,3,1] [3,1,2] [3,2,1]
경우의 수 3! 3*2*1 = 6

파이썬을 이용한 순열 계싼
```python
from itertools import permutations

arr = ['A','B','C']
# 원소 중에서 2개를 뽑는 모든 순열 계산
result = list(permutations(arr,2))
print(result)
```

조합(Combination)
서로 다른 n개에서 r개를 중복 없이 순서를 고려하지 않고 뽑는 것을 의미한다
모든 조합의 수(경우의 수)는 다음의 공식으로 계싼할 수 있다.
조합의 수 공식
nCr = n! / r!(n-r)! = nCn-r

조합의 예시
샴 네트워크
샴 네트워크는 딥러닝 아키텍처 중에서 두 개의 이미지를 받아서 두 이미지가 유사하다면 1을 다르다면 0을 출력한다
이때 n개의 이미지로 구성된 데이터 세트가 있을 때, 매번 2개의 이미지를 뽑아서 2개의 이미지를 네트워크의 입력으로 넣는다. 이 경우, 두 이미지에 대하여 순서는 상관없다.

예를 들어 4개의 이미지가 있을 때 순서를 고려하지 않고 2개의 이미지를 뽑는 경우의 수는?
4*3/2
```python
from itertools import combinations
arr = ['A','B','C']
# 원소 중에서 2개를 뽑는 모든 조합 계산
result = list(combinations(arr,2))
```

중복 순열 (Permutation with Repetition)
서로 다른 n개에서 중복을 포함해 r개를 뽑아 특정한 순서로 나열하는 것을 의미한다.
모든 중복 순열의 수는 다음의 공식으로 계산 가능하다
중복 순열의 수 공식
$n \PI r = n^r$
1, 2, 3을 이용해 만들 수 있는 두 자리 자연수의 개수는?
모든 경우:11,12,13,21,22,23,31,32,33
경우의수 3**2 = 9

파이썬 이용
```python
from itertools import product
arr = ["A",'B','C']
result = list(product(2,arr))
```

중복 조합(Combination with Repetition)
서로 다른 n개에서 중복을 포함해 순서를 고려하지 않고 r개를 뽑는 것을 의미한다.
모든 중복 조합의 수는 다음의 공식으로 계산할 수 있다.
중복 조합의 수 공식
$_n H_r = _{n+r-1} C_r$

사용처
딥러닝에서는 학습된 여러 모델의 결과를 활용하여 최종적인 결과를 생성하는 앙상블 방법이 존재하는데
4개의 딥러닝 모델에서 출력한 값을 평균을 낸 값으로 실제 결과를 추측

서로다른 딥러닝 아키텍처가 3개 존재하면
중복을 허용해 4개를 골라 딥러닝 모델 4개를 합습시킨다
여기서 학습 가능한 조합의 수는?
같은 아키텍처를 여러번 사용하거나 선택하지 않은 아키텍처가 있어도 된다.

```python
from itertools import combinations_with_replacement
a = ['A','B','C']
result = list(combinations_with_replacement(arr,2))
```

확률
S를 전체 사건의 집합(표본 공간=sample space)라고 하면
사전 X가 일어날 확률은 P(X)는 다음과 같다
P(X) = 사건 X가 일어나는 경우의수 / 전체 경우의 수 = n(X)/n(S)

앞면에 1, 뒷면에 0이 쓰여 있는 2개의 동전을 2번 던졌을 때, 눈금의 합이 1일 확률은? 1/2

통계적 확률
주사위를 던졌을 때 눈금이 5개 나올 확률은 1/6다.
그렇다면 6번 던졌을 때 반드시 눈금이 5인 경우가 나올까?
시행 횟수가 적기 때문에 장담할 수 없다.
하지만 6000번 던졌다면 1000번에 가까운 횟수로 1/6이 될것이다.

동일한 시행을 N번 반복해 사건 X가 발생한 횟수를 R이라고 하면
시행 횟수 N을 무한히 크게 만들었을 때, R/N이 수렴하는 값을 사건 X의 통계적 확률이라고 한다.

프로그램을 이용해 많은 시행을 수행하여 확률을 계산해 볼 수 있다.

사례
생성 모델은 실제로 존재하지 않지만, 그럴싸한 이미지를 만들 수 있다.

# 확률 변수와 확률 분포
시행(Trial)과 사건(Event)
시행(trial):반복할 수 있으며, 매번 결과가 달라질 수 있는 실험 ex)주사위를 2개를 던지는 행동
사건(event):시행에 따른 결과를 의미 ex)눈금의 합이 7이 되는 사건

확률은 어떠한 사건(event)이 일어날 가능성을 수로 표현한 것이다.
주사위 2개를 던졌을 때, 눈금의 합이 7이 나올 확률을 구하고 싶다면
이러한 문제를 수식으로 표현을 어떻게 하나

사건을 변수의 형태로 표현한다면 확률을 보다 표현하기 간단할 것이다.

확률 변수란 사건으로 인해 그 값이 확률적으로 정해지는 변수를 의미한다.
주사위 2개를 던지는 시행을 할 때마다 눈금의 합이 변할 수 있다.
따라서 "확률 변수 = 눈금의 합"으로 표현할 수있다.
확률 변수는 대문자 X로 표기하고, 확률 변수가 취할 수 있는 값은 소문자 x로 표현한다.

확률 변수란 시행할 때 마다 변할 수 있는 값(눈금의 합)
확률 함수란, 확률 변수에 따라서 확률 값을 부여하는 함수를 말한다.
확률 함수는 일반적으로 P라고 표현한다.
주사위 두 개 던지기를 했을 때 눈금의 합이 3이 나올 확률을 1/35이다
이를 다음고 ㅏ같이 표현한다
P(X=3) = 1/36

앞면에 1, 뒷면에 0이 쓰여 있는 2개의 동전이 있다고 하면 
시행: 동전 2개를 동시에 던지기
확률 변수 X: 두 눈금의 합
이때 가능한 X의 값으로는 0,1,2가 있다.
시행할 때마다 X값이 달라질 수 있으므로, 확률적으로 변할 수 있따고 하여 X를 확률 변수라 한다.

2개의 동전을 던지는 시행에 대하여
수학적으로 표현하면
눈금의 합이 0인 사건 P(X=0) = 1/4
눈금의 합이 1인 사건 P(X=1) = 1/2
눈금의 합이 2인 사건 P(X=2) = 1/4

시행: 동전 2개를 동시에 던지기
확률 변수 X: 두 눈금의 합

실제 딥러닝 분야에서 사건은
내가 수집하여 가지고 있는 이미지를 사건(event)로 이해할 수 있다.

이미지 x가 주어졌다면 이 데이터 자체도 발생한 사건으로 볼 수있다.
P(x)는 존재하는 모든 이미지 중에서 이렇게 생긴 x가 나올 확률이다라고 이해할 수 있다.

표본 공간(sample space): 발생 가능한 모든 사건들의 집합
확률 변수는 표본 공간 안에서 특정 확률로 발생하는 사건을 특정한 수치에 대응시키는 함수다.
이때 확률 변수가 취할 수 있는 모든 값 x의 집합을 상태 공간(state space)이라고 한다.

확률 분포(probability distribution)란?
각 사건에 어느 정도의 확률이 할다오디었는지 표현한 정보를 의미한다.
확률 분포를 통해 통계적인 특성을 쉽게 이해할 수 있다.

확률 변수 X가 가지는 값 x에 확률 P(X=x)을 대응시키는 함수를 의미한다.
[참고] 확률 분포 그 자체를 함수로 보고, 확률 분포 함수 P와 같은 의미로 쓰기도 한다.
확률 분포 함수로 대표적인 것으로는 1. 확률질량함수, 2.확률 밀도함수가 있따.
모든 사건에 대하여 확률 분포 함수의 값을 표현한 것을 "확률 분포"로 이해할 수 있다.

확률 변수와 확률 분포 함수를 모두 함수로 이해할 수 있다.
사건 -> 확률 변수 X -> 실수 x 확률 분포 함수(함수) -> 확률 값 P(X=x)

확률 변수 X가 취할 수 있는 모든 값을 셀 수 있는 경우, 이를 이산확률변수라고 한다.
이때 이산확률분포는 이산확률변수의 확률 분포를 의미한다.
주사위를 던졌을 때 나올 수 있는 눈금은 1,2,3,4,5,6중 하나이다.
따라서 이 경우 주사위 눈금의 값은 6개만 존재하므로 이산확률 변수이다.